### ISSUE TITLE
[epic] v2.5

### ISSUE THREAD

**Issue by serbanghita** [JSbenchOrg/client#3]
- [ ] Simplify layout, remove unimplemented and unnecessary fields from UI
- [ ] Refactor `TestCase` and `TestCaseEntry` to have `toJSON`
- [ ] keep the `TestCase` model up to date with UI changes.
